<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Manage Background')?></h3></td>
            <td class="a-right">
            	<button onclick="javascript:location.href='<?php echo $this->getUrl("background/adminhtml_myform/index"); ?>'" class="scalable save" type="button"><span>Add New Background</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit grid">
	<?php 
	$totalbackground = Mage::getModel('background/background')->getCollection()->getItems();
	
	?>
    <table cellspacing="0" id="cmsPageGrid_table" class="data" width="100%">
        <thead>
            <tr class="headings">
                <th width="35%" align="center"><?php echo $this->__('Page Title'); ?></th>
                <th width="20%" align="center"><?php echo $this->__('Page Type'); ?></th>
                <th width="20%" align="center" class=" no-link last"><span class="nobr"><?php echo $this->__('Action'); ?></span></th>
            </tr>
        </thead>
                
        <tbody id="">
        <?php if(count($totalbackground)>=1): ?>
			<?php $i=0; foreach($totalbackground as $i=>$page): ?>
                <tr class="<?php echo ($i%2==0)?"even":"odd"; ?>">
                    <td align="center">
						<?php 
							if($page->getBgType()=="cms"){
								$_page = Mage::getModel('cms/page')->load($page->getPageId());
								echo $_page->getTitle();
							}else{
								$_category = Mage::getModel('catalog/category')->load($page->getPageId());
								echo $_category->getName();
							}
						?>
                        </td>
                    <td align="center">
						<?php 
							if($page->getBgType()=="cms"){
								echo "CMS Page";
							}else{
								echo "Category Page";
							}
						?>
                        </td>
                    <td align="center">
                    <a href="<?php echo $this->getUrl("*/*/editpage/id/{$page->getId()}"); ?>" title="Edit">Edit</a>&nbsp;/&nbsp;<a href="<?php echo $this->getUrl("*/*/delete/id/{$page->getId()}"); ?>" title="Delete">Delete</a>
                    </td>
                </tr>
            <?php $i++; endforeach; ?>
         <?php else: ?>
             <tr class="<?php echo ($i%2==0)?"even":"odd"; ?>">
                <td colspan="3" align="center">No background found.</td>
            </tr>
        <?php endif; ?>
		</tbody>
	</table>
</div>
<style type="text/css">
table tr td,table tr th{
	text-align:center;
	}
</style>